/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edusera.ui.authority;

import edusera.business.profiles.Person;
import edusera.business.directory.ProfessorDirectory;
import edusera.business.profiles.Role;
import edusera.business.directory.StudentDirectory;
import edusera.business.profiles.User;
import edusera.business.directory.UserDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import edusera.Business;
import edusera.ui.misc.BaseJPanel;
import utility.Utility;

/**
 *
 * @author ingale.r
 */
public class AuthorityJPanel extends BaseJPanel {

    /**
     * Creates new form SignUpJPanel
     */
    public AuthorityJPanel(Business business) {
        super(business);
        initComponents();
        initialSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfilePic = new javax.swing.JLabel();
        lblGreetings = new javax.swing.JLabel();
        lblOption4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusera/assets/edusera-user-stock-profile-pic.png"))); // NOI18N
        lblProfilePic.setPreferredSize(new java.awt.Dimension(255, 255));

        lblGreetings.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblGreetings.setText("Hello !");

        lblOption4.setBackground(new java.awt.Color(255, 255, 255));
        lblOption4.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblOption4.setForeground(new java.awt.Color(105, 155, 247));
        lblOption4.setText("Degree Approval >");
        lblOption4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOption4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGreetings)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3649, Short.MAX_VALUE)
                        .addComponent(lblOption4)
                        .addGap(774, 774, 774))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(lblOption4)))
                .addGap(42, 42, 42)
                .addComponent(lblGreetings)
                .addContainerGap(857, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblOption4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOption4MouseClicked
        // TODO add your handling code here:
        Utility.switchPanel(new DegreeApprovalJPanel(business), business.getWorkArea());
    }//GEN-LAST:event_lblOption4MouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblOption4;
    private javax.swing.JLabel lblProfilePic;
    // End of variables declaration//GEN-END:variables

    private void initialSetup() {
        // Adjust icon resolution
        ImageIcon ii = new ImageIcon("/Users/ingale.r/NetBeansProjects/edusera/src/edusera/assets/edusera-user-stock-profile-pic.png");
        Image image = ii.getImage().getScaledInstance(225, 225, Image.SCALE_SMOOTH);
        lblProfilePic.setIcon(new ImageIcon(image));
        
        // Display greetings
        lblGreetings.setText("Hello AUTHORITY!");
        
        // Display Options
      

    }    
}
