/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edusera.ui.professor;

import edusera.business.professor.Course;
import edusera.business.professor.CourseCatalog;
import edusera.business.professor.CourseOffering;
import edusera.business.directory.ProfessorDirectory;
import edusera.business.schedule.Semester;
import edusera.business.directory.UserDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import edusera.Business;
import edusera.ui.misc.BaseJPanel;
import utility.Utility;
import utility.Validations;


/**
 *
 * @author ingale.r
 */
public class CourseOfferingJPanel extends BaseJPanel {

    public CourseOfferingJPanel(Business business) {
        super(business);
        initComponents();
        initSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCRN = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        listSemester = new javax.swing.JComboBox<>();
        listCourse = new javax.swing.JComboBox<>();
        lblRegion = new javax.swing.JLabel();
        txtRegion = new javax.swing.JTextField();
        lblLanguage = new javax.swing.JLabel();
        txtLanguage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Course Offering");

        jLabel3.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Course To Be Offered:");

        jLabel4.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CRN : ");

        jLabel5.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("No. of Seats : ");

        jLabel6.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Semester :");

        txtCRN.setForeground(new java.awt.Color(0, 0, 0));

        txtSeats.setForeground(new java.awt.Color(0, 0, 0));

        btnSubmit.setBackground(new java.awt.Color(105, 155, 247));
        btnSubmit.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        listSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSemesterActionPerformed(evt);
            }
        });

        listCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCourseActionPerformed(evt);
            }
        });

        lblRegion.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        lblRegion.setForeground(new java.awt.Color(0, 0, 0));
        lblRegion.setText("Region :");

        txtRegion.setForeground(new java.awt.Color(0, 0, 0));

        lblLanguage.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        lblLanguage.setForeground(new java.awt.Color(0, 0, 0));
        lblLanguage.setText("Langugage :");

        txtLanguage.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("STHeiti", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("<html> <head>     <title>Professor Course Offering Disclaimer</title> </head> <body>     <h1>Course Offering Disclaimer</h1>     <p>Before offering this course to students, please read and acknowledge the following terms and conditions:</p>     <ol>         <li><strong>Course Content:</strong> Ensure that the course content, schedule, and grading criteria are clearly communicated to students. Consistency and transparency are essential for a positive learning experience.</li>         <li><strong>Academic Integrity:</strong> Uphold the university's standards of academic integrity and ethics. Report any instances of plagiarism, cheating, or academic misconduct promptly.</li>         <li><strong>Student Support:</strong> Be available to provide guidance and support to your students throughout the course. Respond to inquiries in a timely manner and offer assistance when needed.</li>         <li><strong>Grading and Evaluation:</strong> Fair and consistent grading is crucial. Ensure that assignments and exams are evaluated objectively and that grades are communicated clearly to students.</li>         <li><strong>Course Evaluation:</strong> Encourage student feedback and evaluations to help improve the course in the future. Use this information to make necessary adjustments for better learning outcomes.</li>     </ol>     <p>By proceeding, you acknowledge that you have read and agreed to the terms and conditions outlined above. Offering a course is a commitment to the education and success of your students, and your adherence to these guidelines is essential for a positive academic experience.</p>    </body> </html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(512, 512, 512)
                        .addComponent(jLabel1)
                        .addGap(1200, 1200, 1200))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(139, 139, 139)
                                            .addComponent(jLabel4))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(lblRegion)
                                            .addComponent(lblLanguage))))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRegion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCRN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listCourse, javax.swing.GroupLayout.Alignment.LEADING, 0, 193, Short.MAX_VALUE)
                                    .addComponent(txtSeats, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLanguage)
                                    .addComponent(listSemester, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtCRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRegion)
                            .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLanguage)
                            .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(listSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(893, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Course toBeOffered = (Course)listCourse.getSelectedItem();
        String crn = txtCRN.getText();
        String region = txtRegion.getText();
        String language = txtLanguage.getText();
        String numOfSeats = txtSeats.getText();
        Semester sem = (Semester)listSemester.getSelectedItem();
        
         if(!checkValidate()){
            JOptionPane.showMessageDialog(this, "Please enter all the details!");
            return;
        }
        
        business.createOffering(toBeOffered, crn, Integer.parseInt(numOfSeats),sem,region,language);
        JOptionPane.showMessageDialog(this, "Course is succesfully offered !!");

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void listCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listCourseActionPerformed

    private void listSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listSemesterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JComboBox<String> listCourse;
    private javax.swing.JComboBox<String> listSemester;
    private javax.swing.JTextField txtCRN;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtSeats;
    // End of variables declaration//GEN-END:variables

    private void initSetup() {
        Utility.addToComboBox(listCourse, business.getCourseList());
        Utility.addToComboBox(listSemester, business.getSemesterList());
    }
    
     public boolean checkValidate(){
        return Validations.isStringValid(txtCRN.getText()) &&
        Validations.isNumeric(txtSeats.getText()) &&
        Validations.isStringValid(txtRegion.getText()) &&
        Validations.isStringValid(txtLanguage.getText());
        
    }
}
