/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edusera.ui.professor;

import edusera.business.professor.Course;
import edusera.business.professor.CourseCatalog;
import edusera.business.professor.CourseOffering;
import edusera.business.directory.ProfessorDirectory;
import edusera.business.students.SeatAssignment;
import edusera.business.schedule.Semester;
import edusera.business.directory.UserDirectory;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.nio.charset.StandardCharsets;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import edusera.Business;
import edusera.Business.StudentsAssignments;
import edusera.ui.misc.BaseJPanel;
import utility.Utility;


/**
 *
 * @author ingale.r
 */
public class GradeStudentJPanel extends BaseJPanel {

    public GradeStudentJPanel(Business business) {
        super(business);
        initComponents();
        initSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCourseOffered = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        listCourse = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentsGrades = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Grade Students ");

        lblCourseOffered.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        lblCourseOffered.setForeground(new java.awt.Color(0, 0, 0));
        lblCourseOffered.setText("Course Offered:");

        btnSubmit.setBackground(new java.awt.Color(105, 155, 247));
        btnSubmit.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Save");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        listCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCourseMouseClicked(evt);
            }
        });
        listCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCourseActionPerformed(evt);
            }
        });

        tblStudentsGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Students", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblStudentsGrades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblStudentsGradesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblStudentsGradesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudentsGrades);
        if (tblStudentsGrades.getColumnModel().getColumnCount() > 0) {
            tblStudentsGrades.getColumnModel().getColumn(0).setResizable(false);
            tblStudentsGrades.getColumnModel().getColumn(1).setResizable(false);
        }

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(655, 655, 655)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCourseOffered)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14281, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseOffered)
                    .addComponent(listCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(463, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Course offered = (Course)listCourse.getSelectedItem();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void listCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCourseActionPerformed

    }//GEN-LAST:event_listCourseActionPerformed

    private void listCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCourseMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_listCourseMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:  
        populateTable();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblStudentsGradesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblStudentsGradesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int selectedRowIndex = tblStudentsGrades.getSelectedRow();
        
            if(selectedRowIndex < 0)
                JOptionPane.showMessageDialog(this, "Please select a row to update");
            else{
                DefaultTableModel model = (DefaultTableModel) tblStudentsGrades.getModel();
                // Get Data from table
                StudentsAssignments studentAssignment = (StudentsAssignments)model.getValueAt(selectedRowIndex, 0);
                Double grade = Double.parseDouble(model.getValueAt(selectedRowIndex, 1).toString());
                // Associate Grade
                System.out.println(grade + "" + studentAssignment);
                studentAssignment.assignment.setGrade(grade);
            }
        }
    }//GEN-LAST:event_tblStudentsGradesKeyPressed

    private void tblStudentsGradesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblStudentsGradesKeyReleased

    }//GEN-LAST:event_tblStudentsGradesKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseOffered;
    private javax.swing.JComboBox<String> listCourse;
    private javax.swing.JTable tblStudentsGrades;
    // End of variables declaration//GEN-END:variables

    private void initSetup() {
        Utility.addToComboBox(listCourse, business.getOfferingsByProfessor());
    }
    
    private void populateTable() {
    
        DefaultTableModel model = (DefaultTableModel) tblStudentsGrades.getModel();
        model.setRowCount(0);
   
        List<StudentsAssignments> ls = business.getAllStudentsByOfferings((CourseOffering)listCourse.getSelectedItem(),business.getCurrent());

        for (StudentsAssignments studentAssignment : ls){
            Object[] row = new Object[5];
            row[0] = studentAssignment;
            row[1] = studentAssignment.assignment.getGrade();
            model.addRow(row);
    }
  }
}
