/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edusera.ui.professor;

import edusera.business.professor.Course;
import edusera.business.professor.CourseCatalog;
import edusera.business.professor.CourseOffering;
import edusera.business.profiles.Person;
import edusera.business.directory.ProfessorDirectory;
import edusera.business.profiles.Role;
import edusera.business.schedule.Semester;
import edusera.business.directory.StudentDirectory;
import edusera.business.profiles.User;
import edusera.business.directory.UserDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import edusera.Business;
import edusera.ui.misc.BaseJPanel;
import utility.Utility;
import static utility.Utility.imageResize;

/**
 *
 * @author ingale.r
 */
public class ProfJPanel extends BaseJPanel {

    public ProfJPanel(Business business) {
        super(business);
        initComponents();
        initialSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfilePic = new javax.swing.JLabel();
        lblGreetings = new javax.swing.JLabel();
        lblOption4 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblCreateCourse = new javax.swing.JLabel();
        lblCourseOffer = new javax.swing.JLabel();
        lblCourseOffer2 = new javax.swing.JLabel();
        lblRating = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusera/assets/edusera-user-stock-profile-pic.png"))); // NOI18N
        lblProfilePic.setPreferredSize(new java.awt.Dimension(255, 255));

        lblGreetings.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblGreetings.setText("Hello !");

        lblOption4.setBackground(new java.awt.Color(255, 255, 255));
        lblOption4.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblOption4.setForeground(new java.awt.Color(105, 155, 247));
        lblOption4.setText("lblOption4");
        lblOption4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOption4MouseClicked(evt);
            }
        });

        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusera/assets/edusera-ongoing-class-profile-pic.png"))); // NOI18N
        lbl1.setPreferredSize(new java.awt.Dimension(255, 255));

        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusera/assets/edusera-history-image.jpeg"))); // NOI18N
        lbl4.setPreferredSize(new java.awt.Dimension(255, 255));

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusera/assets/edusera-students-image.png"))); // NOI18N
        lbl3.setPreferredSize(new java.awt.Dimension(255, 255));

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusera/assets/edusera-ranking-image.png"))); // NOI18N
        lbl2.setPreferredSize(new java.awt.Dimension(255, 255));

        lblCreateCourse.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblCreateCourse.setForeground(new java.awt.Color(0, 153, 255));
        lblCreateCourse.setText("Create Course >");
        lblCreateCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateCourseMouseClicked(evt);
            }
        });

        lblCourseOffer.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblCourseOffer.setForeground(new java.awt.Color(0, 153, 255));
        lblCourseOffer.setText("Offer Course >");
        lblCourseOffer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCourseOfferMouseClicked(evt);
            }
        });

        lblCourseOffer2.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblCourseOffer2.setForeground(new java.awt.Color(0, 153, 255));
        lblCourseOffer2.setText("Grade Students >");
        lblCourseOffer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCourseOffer2MouseClicked(evt);
            }
        });

        lblRating.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblRating.setText("Your rating is :");
        lblRating.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRatingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGreetings)
                            .addComponent(lblRating, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(194, 194, 194)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCreateCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseOffer2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOption4)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseOffer))
                .addContainerGap(13393, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGreetings)
                        .addGap(3, 3, 3)
                        .addComponent(lblRating))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCourseOffer))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCreateCourse)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourseOffer2)
                            .addComponent(lblOption4))))
                .addContainerGap(835, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblCreateCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateCourseMouseClicked
        //Mouse Click
        Utility.switchPanel(new CreateCourseJPanel(business), business.getWorkArea());     
    }//GEN-LAST:event_lblCreateCourseMouseClicked

    private void lblCourseOfferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCourseOfferMouseClicked
        // TODO add your handling code here:
        Utility.switchPanel(new CourseOfferingJPanel(business), business.getWorkArea());
    }//GEN-LAST:event_lblCourseOfferMouseClicked

    private void lblCourseOffer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCourseOffer2MouseClicked
        // TODO add your handling code here:
        Utility.switchPanel(new GradeStudentJPanel(business), business.getWorkArea());
    }//GEN-LAST:event_lblCourseOffer2MouseClicked

    private void lblOption4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOption4MouseClicked
        // TODO add your handling code here:
        Utility.switchPanel(new TeachingHistoryJPanel(business), business.getWorkArea());
    }//GEN-LAST:event_lblOption4MouseClicked

    private void lblRatingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRatingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRatingMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblCourseOffer;
    private javax.swing.JLabel lblCourseOffer2;
    private javax.swing.JLabel lblCreateCourse;
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblOption4;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JLabel lblRating;
    // End of variables declaration//GEN-END:variables

    private void initialSetup() {
        // Adjust icon resolution
        
        imageResize(lblProfilePic, "./src/edusera/assets/edusera-user-stock-profile-pic.png");
   
        
        // Display greetings d
        lblGreetings.setText("Hello Prof."+ business.getLoggedInUser().getPerson().getName());
        
        lblRating.setText("Rating: "+this.updateRating(business.getCurrent()));
        // Display Options
        imageResize(lbl1, "./src/edusera/assets/edusera-ongoing-class-profile-pic.png");
       // lblOption1.setText("Ongoing Class >");
    
        
       imageResize(lbl3, "./src/edusera/assets/edusera-students-image.png");
      // lblOption3.setText("Students >");
      
       imageResize(lbl4, "./src/edusera/assets/edusera-history-image.jpeg");
       lblOption4.setText("Teaching History >");
       
       

    }    
    
    public double updateRating(Semester current){
        double rating = business.calculateMyRatingBySemester(current);
        return rating;
    }
}
