/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edusera.ui.student;

import com.itextpdf.text.DocumentException;
import edusera.business.degree.Authority;
import edusera.business.professor.Course;
import edusera.business.professor.CourseCatalog;
import edusera.business.professor.CourseOffering;
import edusera.business.degree.Degree;
import edusera.business.directory.ProfessorDirectory;
import edusera.business.students.SeatAssignment;
import edusera.business.schedule.Semester;
import edusera.business.students.Student;
import edusera.business.directory.UserDirectory;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.nio.charset.StandardCharsets;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import edusera.Business;
import edusera.Business.CourseRating;
import edusera.Business.StudentsAssignments;
import edusera.ui.misc.BaseJPanel;
import utility.PDFExporter;
import utility.Utility;


/**
 *
 * @author ingale.r
 */
public class ViewCertificatesJPanel extends BaseJPanel {

    public ViewCertificatesJPanel(Business business) {
        super(business);
        initComponents();
        initSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblDegreeList = new javax.swing.JComboBox<>();
        btnGraduate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCertificate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("View Certificate");

        btnSubmit.setBackground(new java.awt.Color(105, 155, 247));
        btnSubmit.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Save");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnGraduate.setText("Ready to Graduate ?");
        btnGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("STHeiti", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("<html> <head>     <title>Disclaimer for Graduation Application Submission</title> </head> <body>     <h2>Disclaimer for Graduation Application Submission</h2>     <p>Before you click on \"Send my Application for Graduation,\" please take a moment to read and understand the following important information:</p>     <ol>         <li><strong>Final Review:</strong> Ensure that you have carefully reviewed your application for graduation. Any errors or omissions may result in delays or complications in the graduation process.</li>         <li><strong>Academic Requirements:</strong> Confirm that you have met all academic requirements and prerequisites for graduation as outlined by your institution. Submission of an application does not guarantee graduation if these requirements are not met.</li>     </ol>     <p>By clicking \"Send my Application for Graduation,\" you acknowledge that you have read, understood, and complied with the above points. You are responsible for any consequences arising from errors, omissions, or failure to meet the requirements outlined.</p>     <p>Please ensure that you have thoroughly reviewed your application before proceeding. Graduation is a significant milestone, and your attention to these details will help ensure a smooth and successful graduation process.</p> </body> </html>");

        btnCertificate.setText("Download Certificate");
        btnCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCertificateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDegreeList, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGraduate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCertificate))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14044, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGraduate)
                        .addComponent(lblDegreeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCertificate))
                .addGap(448, 448, 448)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
     //   Course offered = (Course)listCourse.getSelectedItem();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduateActionPerformed
        // TODO add your handling code here:
        Degree thisDegree = (Degree)lblDegreeList.getSelectedItem();
        if(thisDegree.canStudentGraduate((Student)business.getLoggedInUser().getPerson())){
         JOptionPane.showMessageDialog(this, "You have passed all the criteria to graduate. Your Application is sent for processing!");
         Authority authority = business.getAuth();
         Student stud = (Student)this.business.getLoggedInUser().getPerson();
         stud.setDegree(thisDegree);
         authority.addStudentToGraduateQueue(stud);
         stud.setSubmitted(true);
         initSetup();
        }
        else
            JOptionPane.showMessageDialog(this, "You are not eligible for Graduation!!");

    }//GEN-LAST:event_btnGraduateActionPerformed

    private void btnCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCertificateActionPerformed
        try {
            // TODO add your handling code here:
            PDFExporter.certficateExport((Student)business.getLoggedInUser().getPerson());
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCertificatesJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            java.util.logging.Logger.getLogger(ViewCertificatesJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCertificateActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCertificate;
    private javax.swing.JButton btnGraduate;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> lblDegreeList;
    // End of variables declaration//GEN-END:variables

    private void initSetup() {
        Student stud = (Student)business.getLoggedInUser().getPerson();
        if(stud.isSubmitted() || stud.isGraduated()){
            btnGraduate.setEnabled(false);
        }
        else
        {
            btnGraduate.setEnabled(true);
            btnCertificate.setEnabled(false);
        
        }
        
        if( stud.isGraduated())
            btnCertificate.setEnabled(true);
        
        Utility.addToComboBox(lblDegreeList, business.getDegreeRegistry().getDegrees()); 
        
    }
}