/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edusera.ui.admin;

import edusera.business.profiles.Person;
import edusera.business.directory.ProfessorDirectory;
import edusera.business.profiles.Role;
import edusera.business.directory.StudentDirectory;
import edusera.business.profiles.User;
import edusera.business.directory.UserDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import edusera.Business;
import edusera.ui.misc.BaseJPanel;
import utility.Utility;

/**
 *
 * @author ayush
 */
public class AdminJPanel extends BaseJPanel {

    /**
     * Creates new form SignUpJPanel
     */
    public AdminJPanel(Business business) {
        super(business);
        initComponents();
        initialSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfilePic = new javax.swing.JLabel();
        lblGreetings = new javax.swing.JLabel();
        lblOption1 = new javax.swing.JLabel();
        lblOption2 = new javax.swing.JLabel();
        lblPerformance = new javax.swing.JLabel();
        lblOption3 = new javax.swing.JLabel();
        lblOption4 = new javax.swing.JLabel();
        lblOption5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusera/assets/edusera-user-stock-profile-pic.png"))); // NOI18N
        lblProfilePic.setPreferredSize(new java.awt.Dimension(255, 255));

        lblGreetings.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblGreetings.setText("Hello !");

        lblOption1.setBackground(new java.awt.Color(255, 255, 255));
        lblOption1.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblOption1.setForeground(new java.awt.Color(105, 155, 247));
        lblOption1.setText("Manage Students >");
        lblOption1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOption1MouseClicked(evt);
            }
        });

        lblOption2.setBackground(new java.awt.Color(255, 255, 255));
        lblOption2.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblOption2.setForeground(new java.awt.Color(105, 155, 247));
        lblOption2.setText("Manage Professors >");
        lblOption2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOption2MouseClicked(evt);
            }
        });

        lblPerformance.setBackground(new java.awt.Color(255, 255, 255));
        lblPerformance.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblPerformance.setForeground(new java.awt.Color(105, 155, 247));
        lblPerformance.setText("Performance Indices >");
        lblPerformance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPerformanceMouseClicked(evt);
            }
        });

        lblOption3.setBackground(new java.awt.Color(255, 255, 255));
        lblOption3.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblOption3.setForeground(new java.awt.Color(105, 155, 247));
        lblOption3.setText("Manage Users >");
        lblOption3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOption3MouseClicked(evt);
            }
        });

        lblOption4.setBackground(new java.awt.Color(255, 255, 255));
        lblOption4.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblOption4.setForeground(new java.awt.Color(105, 155, 247));
        lblOption4.setText("Manage Degree >");
        lblOption4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOption4MouseClicked(evt);
            }
        });

        lblOption5.setBackground(new java.awt.Color(255, 255, 255));
        lblOption5.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblOption5.setForeground(new java.awt.Color(105, 155, 247));
        lblOption5.setText("Manage Semester >");
        lblOption5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOption5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGreetings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPerformance)
                    .addComponent(lblOption1)
                    .addComponent(lblOption4))
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOption2)
                    .addComponent(lblOption3)
                    .addComponent(lblOption5))
                .addGap(276, 276, 276))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGreetings))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOption4)
                            .addComponent(lblOption5))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOption2)
                            .addComponent(lblOption1))
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOption3)
                            .addComponent(lblPerformance))))
                .addContainerGap(744, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblPerformanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPerformanceMouseClicked
        // TODO add your handling code here:
        Utility.switchPanel(new PerformanceIndices(business), business.getWorkArea());

    }//GEN-LAST:event_lblPerformanceMouseClicked

    private void lblOption1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOption1MouseClicked
        // TODO add your handling code here:
       Utility.switchPanel(new ManageStudentsJPanel(business), business.getWorkArea());

    }//GEN-LAST:event_lblOption1MouseClicked

    private void lblOption2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOption2MouseClicked
        // TODO add your handling code here:
        Utility.switchPanel(new ManageProfessorJPanel(business), business.getWorkArea());

    }//GEN-LAST:event_lblOption2MouseClicked

    private void lblOption3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOption3MouseClicked
        // TODO add your handling code here:
       Utility.switchPanel(new ManageUserJPanel(business), business.getWorkArea());

    }//GEN-LAST:event_lblOption3MouseClicked

    private void lblOption4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOption4MouseClicked
        // TODO add your handling code here:
        Utility.switchPanel(new ManageDegreesNewJPanel(business), business.getWorkArea());
    }//GEN-LAST:event_lblOption4MouseClicked

    private void lblOption5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOption5MouseClicked
        // TODO add your handling code here:
         Utility.switchPanel(new ManageSemesterJPanel(business), business.getWorkArea());
    }//GEN-LAST:event_lblOption5MouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblOption1;
    private javax.swing.JLabel lblOption2;
    private javax.swing.JLabel lblOption3;
    private javax.swing.JLabel lblOption4;
    private javax.swing.JLabel lblOption5;
    private javax.swing.JLabel lblPerformance;
    private javax.swing.JLabel lblProfilePic;
    // End of variables declaration//GEN-END:variables

    private void initialSetup() {
        // Adjust icon resolution
        ImageIcon ii = new ImageIcon("/Users/ayush/NetBeansProjects/edusera/src/edusera/assets/edusera-user-stock-profile-pic.png");
        Image image = ii.getImage().getScaledInstance(225, 225, Image.SCALE_SMOOTH);
        lblProfilePic.setIcon(new ImageIcon(image));
        
        // Display greetings
        lblGreetings.setText("Hello ADMIN!");
        
        // Display Options
        lblOption1.setText("Manage Students >");
        lblOption2.setText("Manage Professors >");
        lblOption3.setText("Manage Users >");

    }    
}
