/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edusera.ui.admin;

import edusera.business.professor.Course;
import edusera.business.professor.CourseCatalog;
import edusera.business.professor.CourseOffering;
import edusera.business.directory.ProfessorDirectory;
import edusera.business.students.SeatAssignment;
import edusera.business.schedule.Semester;
import edusera.business.directory.UserDirectory;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.nio.charset.StandardCharsets;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import edusera.Business;
import edusera.Business.CompleteTeachingHistory;
import edusera.Business.CourseRating;
import edusera.Business.ProfessorRating;
import edusera.Business.StudentsAssignments;
import edusera.Business.StudentsRating;
import edusera.Business.TopCourseRating;
import edusera.ui.misc.BaseJPanel;
import utility.Utility;


/**
 *
 * @author ayush
 */
public class PerformanceIndices extends BaseJPanel {
    
     private boolean isTablePopulated = false;

    public PerformanceIndices(Business business) {
        super(business);
        initComponents();
       // initSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerformances = new javax.swing.JTable();
        btnTopStudents = new javax.swing.JButton();
        btnTopProfessors = new javax.swing.JButton();
        btnTopCourses = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Top Performances");

        tblPerformances.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPerformances.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblPerformancesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblPerformancesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblPerformances);
        if (tblPerformances.getColumnModel().getColumnCount() > 0) {
            tblPerformances.getColumnModel().getColumn(0).setResizable(false);
            tblPerformances.getColumnModel().getColumn(1).setResizable(false);
        }

        btnTopStudents.setBackground(new java.awt.Color(105, 155, 247));
        btnTopStudents.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        btnTopStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnTopStudents.setText("Top 3 Students");
        btnTopStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTopStudentsMouseClicked(evt);
            }
        });

        btnTopProfessors.setBackground(new java.awt.Color(105, 155, 247));
        btnTopProfessors.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        btnTopProfessors.setForeground(new java.awt.Color(255, 255, 255));
        btnTopProfessors.setText("Top 3 Professors");
        btnTopProfessors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTopProfessorsMouseClicked(evt);
            }
        });
        btnTopProfessors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopProfessorsActionPerformed(evt);
            }
        });

        btnTopCourses.setBackground(new java.awt.Color(105, 155, 247));
        btnTopCourses.setFont(new java.awt.Font("STHeiti", 1, 18)); // NOI18N
        btnTopCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnTopCourses.setText("Top 3 Courses");
        btnTopCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTopCoursesMouseClicked(evt);
            }
        });
        btnTopCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopCoursesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTopStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTopProfessors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTopCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(636, 636, 636)
                        .addComponent(jLabel1)))
                .addContainerGap(14002, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnTopStudents)
                        .addGap(51, 51, 51)
                        .addComponent(btnTopProfessors)
                        .addGap(61, 61, 61)
                        .addComponent(btnTopCourses)))
                .addContainerGap(881, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblPerformancesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPerformancesKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tblPerformancesKeyPressed

    private void tblPerformancesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPerformancesKeyReleased

    }//GEN-LAST:event_tblPerformancesKeyReleased

    private void btnTopCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTopCoursesActionPerformed

    private void btnTopProfessorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopProfessorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTopProfessorsActionPerformed

    private void btnTopStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopStudentsMouseClicked
        // TODO add your handling code here:
        populateTop3Students();
        
    }//GEN-LAST:event_btnTopStudentsMouseClicked

    private void btnTopProfessorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopProfessorsMouseClicked
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnTopProfessorsMouseClicked

    private void btnTopCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopCoursesMouseClicked
        // TODO add your handling code here:
        populateTop3Courses();
    }//GEN-LAST:event_btnTopCoursesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTopCourses;
    private javax.swing.JButton btnTopProfessors;
    private javax.swing.JButton btnTopStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPerformances;
    // End of variables declaration//GEN-END:variables

    private void initSetup() {
             
            populateTable();   
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPerformances.getModel();
        model.setRowCount(0);

        List<ProfessorRating> topProfessors = business.topProfessors(); // Assuming you have a method to get the top professors

        for (ProfessorRating professorRating : topProfessors) {
            Object[] row = new Object[2];
            row[0] = professorRating.professor.getName(); 
            row[1] = professorRating.rating;
            model.addRow(row);
        }
    }
    
    private void populateTop3Students() {
        DefaultTableModel model = (DefaultTableModel) tblPerformances.getModel();
        model.setRowCount(0);

        List<StudentsRating> topStudents = business.topStudents(); // Assuming you have a method to get the top professors

        for (StudentsRating studentsRating : topStudents) {
            Object[] row = new Object[2];
            row[0] = studentsRating.student;
            row[1] = studentsRating.grade;
            model.addRow(row);
        }
    }
    
     private void populateTop3Courses() {
        DefaultTableModel model = (DefaultTableModel) tblPerformances.getModel();
        model.setRowCount(0);

        List<TopCourseRating> topCourses = business.topCourses(); // Assuming you have a method to get the top professors

        for (TopCourseRating topCourse : topCourses) {
            Object[] row = new Object[2];
            row[0] = topCourse.courseOffer;
            row[1] = topCourse.rating;
            model.addRow(row);
        }
    }
}
