/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edusera.ui.employer;

import edusera.business.profiles.Person;
import edusera.business.directory.ProfessorDirectory;
import edusera.business.profiles.Role;
import edusera.business.directory.StudentDirectory;
import edusera.business.profiles.User;
import edusera.business.directory.UserDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import edusera.Business;
import edusera.ui.misc.BaseJPanel;
import utility.Utility;
import static utility.Utility.imageResize;

/**
 *
 * @author ingale.r
 */
public class EmployerJPanel extends BaseJPanel {

    public EmployerJPanel(Business business) {
        super(business);
        initComponents();
        initialSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfilePic = new javax.swing.JLabel();
        lblGreetings = new javax.swing.JLabel();
        lblOption3 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lblRateStudent = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusera/assets/edusera-user-stock-profile-pic.png"))); // NOI18N
        lblProfilePic.setPreferredSize(new java.awt.Dimension(255, 255));

        lblGreetings.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblGreetings.setText("Hello Employer!");

        lblOption3.setBackground(new java.awt.Color(255, 255, 255));
        lblOption3.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblOption3.setForeground(new java.awt.Color(105, 155, 247));
        lblOption3.setText("Students");
        lblOption3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOption3MouseClicked(evt);
            }
        });

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edusera/assets/edusera-students-image.png"))); // NOI18N
        lbl3.setPreferredSize(new java.awt.Dimension(255, 255));

        lblRateStudent.setFont(new java.awt.Font("STHeiti", 1, 24)); // NOI18N
        lblRateStudent.setForeground(new java.awt.Color(0, 153, 255));
        lblRateStudent.setText("Rate Students >");
        lblRateStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRateStudentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(lblGreetings))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(lblRateStudent)
                                .addGap(161, 161, 161)
                                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(512, 512, 512)
                                .addComponent(lblOption3)))))
                .addGap(13202, 13331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRateStudent)
                                .addGap(92, 92, 92))
                            .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGreetings)))
                .addContainerGap(852, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblRateStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRateStudentMouseClicked
        //Mouse Click
        Utility.switchPanel(new RateStudentsJPanel(business), business.getWorkArea());       
    }//GEN-LAST:event_lblRateStudentMouseClicked

    private void lblOption3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOption3MouseClicked
        Utility.switchPanel(new RateStudentsJPanel(business), business.getWorkArea());
    }//GEN-LAST:event_lblOption3MouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblOption3;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JLabel lblRateStudent;
    // End of variables declaration//GEN-END:variables

    private void initialSetup() {
        // Adjust icon resolution
        
        imageResize(lblProfilePic, "./src/edusera/assets/edusera-user-stock-profile-pic.png");
   
        
        // Display greetings dEmployer
        lblGreetings.setText(business.getLoggedInUser().getPerson().getName());
        
        // Display Options
        imageResize(lbl3, "/Users/ingale.r/NetBeansProjects/assignment-3-teamaar23/src/edusera/assets/edusera-ongoing-class-profile-pic.png");
        lblRateStudent.setText("Rate Students >");
        
       
       

    }    
}
